FROM ubuntu:18.04
MAINTAINER pbrian
LABEL Name="pbriandev" Version=0.0.1

### Constants
ENV WKDIR /staging
ENV USERHOME /home/pbrian
ENV USERNAME pbrian
ENV USERFULLNAME "Paul Brian"
RUN mkdir $WKDIR

#Investigate this more
ENV DEBIAN_FRONTEND=noninteractive

{{ apt }}

{{ baseconfig }}

{{ otherdevtools }}

{{ sshX }}

{{ user }}

{{ py3 }}

{{ emacs }}

{{ latex }}

EXPOSE 22
ENTRYPOINT ["/home/pbrian/ENTRYPOINT.sh"]


